--- #YAML:1.0
name:               Catalyst-Helper-Controller-Scaffold-HTML-Template
version:            0.04
abstract:           Helper for Scaffolding using HTML::Template.
author:
    - Arnaud (Arhuman) Assad <arhuman@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:             5.23
    Catalyst::Plugin::FormValidator:  0
    Catalyst::View::HTML::Template:  0
    Class::DBI::AsForm:   0
    Class::DBI::FromForm:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
