# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Helper-Controller-Scaffold-HTML-Template
version:      0.02
version_from: lib/Catalyst/Helper/Controller/Scaffold/HTML/Template.pm
installdirs:  site
requires:
    Catalyst:                      5.23
    Catalyst::Plugin::FormValidator: 0
    Catalyst::View::HTML::Template: 0
    Class::DBI::AsForm:            0
    Class::DBI::FromForm:          0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
